version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo_graphql_api_development
      POSTGRES_USER: hogehoge
      POSTGRES_PASSWORD: hogehoge
    ports:
      - 5432:5432
    volumes:
      - ./backend/initdb:/docker-entrypoint-initdb.d
      - ./backend/database:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    volumes:
      - ./backend:/go/src/backend
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    tty: true
    volumes:
      - ./frontend:/frontend
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
